export const staticCityPromise = {
  name: 'STATIC City',
  headline: 'Spawn. Flex. Travel. Shop. Socialize. Broadcast. Return.',
  copy: 'The long-term product loop is a vertical entertainment city where an Entity can spawn from owned property, move through social districts, buy identity items, attend events, and return with status.',
}

export const signatureCityLoop = [
  ['Spawn', 'Wake up in a penthouse near the mountain summit with skyline, wardrobe, inventory, and property access loaded.'],
  ['Valet', 'Head to valet, select a luxury SUV, and choose a route down the mountain.'],
  ['Drive', 'Cruise the strip while STATIC Radio follows the route and billboards react to active events.'],
  ['Shop', 'Enter the mall or Market Walk to preview clothing, jewelry, skins, accessories, and limited drops.'],
  ['Rooftop', 'Ride up to the Radio rooftop, hear what is live, meet Entities, and preview status props like drinks or cigars.'],
  ['Return', 'Save the fit, the social moment, the venue, and the route back to your property or next event.'],
]

export const navigationMapPlan = {
  name: 'STATIC NavMap',
  status: 'planned-ui',
  copy: 'A real-time corner map should eventually show the player position, current district tier, route line, venue pins, property spawns, valet points, event heat, friends, and S.A.G.E. guidance.',
  layers: [
    ['Player', 'Current Entity position, facing direction, and movement mode.'],
    ['Routes', 'Walking, valet, vehicle, elevator, rooftop, and venue approach paths.'],
    ['Venues', 'Signals, LIVE, Radio, PLAY, Studio, Marketplace, Channels, and S.A.G.E. pins.'],
    ['Property', 'Owned spawn points, businesses, homes, penthouses, mansions, suites, and locked landmarks.'],
    ['Events', 'Concert heat, red carpets, creator drops, rooftop sessions, and crowd movement.'],
  ],
  pins: [
    { id: 'spawn', label: 'Penthouse Spawn', type: 'property', x: 68, y: 18 },
    { id: 'valet', label: 'Valet', type: 'route', x: 59, y: 30 },
    { id: 'market', label: 'Market Walk', type: 'venue', x: 45, y: 58 },
    { id: 'radio', label: 'Radio Rooftop', type: 'event', x: 55, y: 43 },
    { id: 'strip', label: 'Street Pulse', type: 'route', x: 29, y: 76 },
  ],
}

export const tenPhaseCityPlan = [
  {
    id: 'city-bible',
    phase: '01',
    title: 'STATIC City Bible',
    status: 'blueprint-now',
    tagline: 'The map before the engine.',
    goal: 'Lock the mountain city layout, district tiers, landmarks, transit logic, property classes, public/private access, and visual laws.',
    deliverables: ['Vertical mountain hierarchy', 'Landmark registry', 'Road and transit logic', 'Soft-gate rules'],
    notYet: ['No live city simulation', 'No real property sales'],
  },
  {
    id: 'create-player',
    phase: '02',
    title: 'Create-a-Player Entity',
    status: 'spec-now',
    tagline: 'The user becomes the network identity.',
    goal: 'Design a real Entity creator for face, body, style, wardrobe, jewelry, animation, mic input, optional voice effects, spawn rules, and cloud persistence.',
    deliverables: ['Identity sculpt spec', 'Wardrobe slots', 'Mic and voice effects plan', 'Rig-ready animation list'],
    notYet: ['No fake saved avatar ownership', 'No forced synthetic voices'],
  },
  {
    id: 'property-spawn',
    phase: '03',
    title: 'Property And Spawn',
    status: 'planned',
    tagline: 'Where your Entity wakes up matters.',
    goal: 'Define starter rooms, apartments, businesses, penthouses, mansions, castles, suites, and landmark spawn properties tied to access and status.',
    deliverables: ['Property tiers', 'Spawn contract', 'Interior preview rules', 'Access and deed model'],
    notYet: ['No fake purchases', 'No fake ownership perks'],
  },
  {
    id: 'vehicle-travel',
    phase: '04',
    title: 'Vehicle And Travel',
    status: 'planned',
    tagline: 'Valet, route, arrival.',
    goal: 'Move from cinematic travel clips into vehicle selection, route choices, valet points, mountain descent, venue arrivals, and eventually controllable driving.',
    deliverables: ['Valet UX', 'Vehicle class list', 'Route camera paths', 'Arrival cutscenes', 'NavMap route line'],
    notYet: ['No fake driving multiplayer', 'No licensed vehicle brands'],
  },
  {
    id: 'mall-market',
    phase: '05',
    title: 'Mall And Marketplace',
    status: 'planned',
    tagline: 'Identity becomes inventory.',
    goal: 'Create the shopping layer for clothes, jewelry, skins, accessories, props, creator drops, memberships, and saveable wishlists before payments.',
    deliverables: ['Mall district map', 'Item taxonomy', 'Wishlist and save flow', 'Drop preview rules'],
    notYet: ['No payment flow', 'No fake transactions'],
  },
  {
    id: 'radio-rooftop',
    phase: '06',
    title: 'STATIC Radio Rooftop',
    status: 'planned',
    tagline: 'The sound of the city.',
    goal: 'Build the rooftop as a social audio venue with stations, host surfaces, ambient city audio, lounges, event simulcasts, and rights-safe programming.',
    deliverables: ['Station UI', 'Rooftop venue logic', 'Simulcast plan', 'Rights and static-made music policy'],
    notYet: ['No unlicensed streams', 'No fake 24/7 radio backend'],
  },
  {
    id: 'social-presence',
    phase: '07',
    title: 'Social Presence',
    status: 'planned',
    tagline: 'The city needs bodies before it needs chaos.',
    goal: 'Start with NPC shells and friend/follow presence, then add real rooms only after auth, moderation, privacy, reporting, and safety are strong.',
    deliverables: ['Presence rules', 'NPC shell contract', 'Friend/follow visibility', 'Moderation gates'],
    notYet: ['No fake multiplayer', 'No fake NPC intelligence'],
  },
  {
    id: 'venue-events',
    phase: '08',
    title: 'Venue Event System',
    status: 'planned',
    tagline: 'Events create movement.',
    goal: 'Make concerts, red carpets, premieres, creator drops, rooftop sessions, and celebrity-style appearances pull people through the city.',
    deliverables: ['Event schema', 'Crowd heat model', 'Event routing', 'Signals aftershock plan'],
    notYet: ['No fake live events', 'No fake tickets'],
  },
  {
    id: 'inventory-status',
    phase: '09',
    title: 'Inventory And Status',
    status: 'planned',
    tagline: 'What you own changes how you move.',
    goal: 'Tie wardrobe, jewelry, vehicles, properties, passes, event attendance, and social reputation into visible status and access.',
    deliverables: ['Inventory schema', 'Status tiers', 'Access checks', 'Moderated display rules'],
    notYet: ['No fake wallet', 'No fake tradable assets'],
  },
  {
    id: 'real-engine',
    phase: '10',
    title: 'Real Engine Upgrade',
    status: 'planned',
    tagline: 'Prototype becomes traversable city.',
    goal: 'Move beyond the current technical prototype into street-level traversal, avatar rigs, pathfinding, optimized scene loading, vehicles, interiors, and eventually multiplayer.',
    deliverables: ['Engine stack decision', 'Scene streaming plan', 'Avatar controller', 'Performance budget', 'Realtime NavMap HUD'],
    notYet: ['No giant engine jump before city rules are locked', 'No uncontrolled cost explosion'],
  },
]

export const nextCityBuildSlices = [
  ['City map bible', 'Turn the hierarchy into a map with roads, districts, landmarks, and spawn layers.'],
  ['Entity builder spec', 'Define body/face/style/wardrobe/mic/effects/animation slots before UI work gets expensive.'],
  ['Penthouse loop prototype', 'Prototype the route: penthouse spawn, valet, mall, Radio rooftop, strip return.'],
  ['NavMap HUD', 'Add the corner map contract for route lines, venue pins, property markers, valet points, and event heat.'],
  ['Access policy', 'Separate public hype, approved beta systems, owner-only dev tools, and future paid systems.'],
]
