export const worldEngineStatus = {
  mode: 'web-preview',
  engine: 'owner-gated-three-prototype',
  version: '0.1.2',
  sceneId: 'static-arrival-district',
  copy: 'The public site is structured as an engine-ready Arrival District. True street-level walking, multiplayer, NPC intelligence, avatar accounts, commerce, and paid generation systems are not active in this build.',
}

export const arrivalCinemaClips = [
  {
    id: 'arrival-walk-01',
    src: '/assets/videos/static-arrival-walk-01.mov',
    label: 'ARRIVAL WALK // 01',
    caption: 'The city opens. Venues light up. STATIC becomes a place.',
    cameraIntent: 'establishing-approach',
  },
  {
    id: 'arrival-walk-02',
    src: '/assets/videos/static-arrival-walk-02.mov',
    label: 'ARRIVAL WALK // 02',
    caption: 'Move through the district before the interface appears.',
    cameraIntent: 'street-level-arrival',
  },
]

export const districtCityScale = {
  id: 'static-mountain-city',
  name: 'STATIC City',
  status: 'planned',
  scaleReference: 'compact vertical entertainment city with the destination density of a strip district and the status climb of a mountain city',
  designRule: 'The bottom is darker, cheaper, louder, and street-driven. A long dark freeway tunnel opens into Tunnel Rise Suburbs, then the climb gets brighter and more premium until Crown Ridge and STATIC Tower crown the summit.',
  zones: [
    { id: 'street-pulse', name: 'Street Pulse', elevation: 'base', purpose: 'Entry-level homes, cheap rentals, first businesses, open Signals, crowded nightlife, darker streets, and the public culture loop.' },
    { id: 'base-loop', name: 'Base Loop', elevation: 'low', purpose: 'A circular strip around the mountain with starter venues, transit, creator pop-ups, Radio spillover, and early player businesses.' },
    { id: 'neon-rise', name: 'Neon Rise', elevation: 'mid', purpose: 'Better apartments, clubs, studios, Channels, PLAY entrances, nicer roads, brighter signage, and visible social status.' },
    { id: 'crown-ridge', name: 'Crown Ridge', elevation: 'high', purpose: 'Luxury architecture, premium hotels, galleries, red-carpet venues, elite lounges, mansions, and celebrity event approaches.' },
    { id: 'summit-tower', name: 'STATIC Tower Summit', elevation: 'summit', purpose: 'Mr. Stone landmark spawn, STATIC Tower, theme park, flagship concert venue, city command view, and the highest-status destination.' },
  ],
}

export const districtLandmarks = [
  ['Arrival Plaza', 'street-pulse', 'Public spawn and first spectacle.'],
  ['Signal Towers', 'base-loop', 'Programmable billboards and cultural pulse.'],
  ['STATIC LIVE Arena', 'neon-rise', 'Entity concerts, premieres, rooms, and audience events.'],
  ['Rooftop Frequency Deck', 'neon-rise', 'Always-on radio and simulcast layer.'],
  ['PLAY Gate', 'base-loop', 'Portal hub for playable worlds and limited modes.'],
  ['Creation Tower', 'crown-ridge', 'Studio, tools, release control, and creator operations.'],
  ['Market Walk', 'base-loop', 'Skins, drops, assets, passes, and future deed previews.'],
  ['Estate Hills Overlook', 'crown-ridge', 'Prestige homes, mansions, castles, and landmark spawns.'],
  ['STATIC Tower', 'summit-tower', 'Mr. Stone-owned summit landmark with theme park, flagship concert venue, red-carpet event floor, and city command view.'],
]

export const cityHierarchyLevels = [
  {
    id: 'street-pulse',
    tier: '01',
    name: 'Street Pulse',
    elevation: 'Base / Dark Ring',
    status: 'entry',
    copy: 'The affordable, crowded, loud, neon-underbelly layer: starter houses, first shops, open creator hustle, street music, and public Signals.',
  },
  {
    id: 'base-loop',
    tier: '02',
    name: 'Base Loop',
    elevation: 'Mountain Ring Road',
    status: 'starter-plus',
    copy: 'The loop circling the mountain: transit, venues, small businesses, cheap offices, creator pop-ups, starter clubs, and first property upgrades.',
  },
  {
    id: 'neon-rise',
    tier: '03',
    name: 'Neon Rise',
    elevation: 'Mid City',
    status: 'rising',
    copy: 'Brighter streets, cleaner architecture, better cars, nicer apartments, Channels, studios, PLAY entrances, Radio lounges, and stronger social status.',
  },
  {
    id: 'crown-ridge',
    tier: '04',
    name: 'Crown Ridge',
    elevation: 'Luxury Ridge',
    status: 'premium',
    copy: 'A luxury ridge around the upper mountain: hotels, red carpets, galleries, elite clubs, villas, mansions, castles, and ceremonial event routes.',
  },
  {
    id: 'summit-tower',
    tier: '05',
    name: 'STATIC Tower',
    elevation: 'Summit',
    status: 'landmark',
    copy: 'Mr. Stone’s summit tower: theme park, largest concert venue, celebrity red-carpet floor, command view, and the symbolic top of the city.',
  },
]

export const createPlayerRoadmap = [
  ['Identity sculpt', 'Face, body, stance, style profile, mic identity, and Entity lore without forcing users into a generic avatar.'],
  ['Wardrobe and status', 'Streetwear, luxury fits, uniforms, jewelry, skins, weapons-as-props, accessories, vehicles, and property-linked cosmetics.'],
  ['Animation rig', 'Walk, idle, talk, emote, dance, stage presence, vehicle entry, venue entry, and S.A.G.E.-guided onboarding animations.'],
  ['Spawn contract', 'Spawn from Arrival Plaza at first, then from owned homes, businesses, penthouses, mansions, castles, or landmark venues.'],
  ['Mic and effects', 'Use the user mic by default, then offer optional voice changers, privacy controls, proximity voice, effects, and moderation rules.'],
  ['Persistence', 'Save avatar, inventory, property access, social graph, privacy, moderation status, and generation provenance before multiplayer scale.'],
]

export const districtVenues = [
  {
    id: 'signals',
    name: 'Signals',
    eyebrow: 'Discovery Boulevard',
    route: '/signals',
    hotspotClass: 'district-hotspot--signals',
    status: 'Culture feed live',
    metric: 'Public pulse',
    copy: 'Short-form drops, creator posts, premieres, clips, releases, and strange new worlds move through this boulevard first.',
    unlocks: ['For-you discovery', 'Public cloud Signals', 'Creator drops'],
    engine: {
      zone: 'discovery-boulevard',
      portalType: 'social-feed',
      spawn: { x: 55, y: 37, z: 0 },
      camera: 'street-feed-pan',
      travelLine: 'north-east-boulevard',
      futureSystems: ['live-feed-panels', 'creator-crowd', 'personalized-billboards', 'event-aftershock-clips', 'social storefronts'],
    },
  },
  {
    id: 'live',
    name: 'STATIC LIVE',
    eyebrow: 'Broadcast Arena',
    route: '/live',
    hotspotClass: 'district-hotspot--live',
    status: 'Rooms warming',
    metric: 'Live floor',
    copy: 'Premieres, watch parties, creator rooms, entity broadcasts, performances, and audience-driven events gather here.',
    unlocks: ['Premiere rooms', 'Entity live mode', 'Event countdowns'],
    engine: {
      zone: 'broadcast-arena',
      portalType: 'event-venue',
      spawn: { x: 72, y: 28, z: 0 },
      camera: 'arena-marquee-push',
      travelLine: 'broadcast-line',
      futureSystems: ['live-stage-presence', 'watch-party-crowds', 'event-ticketing-gate', 'entity-concert-rush', 'venue hospitality suites'],
    },
  },
  {
    id: 'play',
    name: 'STATIC PLAY',
    eyebrow: 'Arcade Worlds',
    route: '/play',
    hotspotClass: 'district-hotspot--play',
    status: 'Prompt engine ready',
    metric: 'Playable ideas',
    copy: 'Describe a game or interactive world, then move from idea to saved concept without leaving the network.',
    unlocks: ['Prompt UI', 'World cards', 'Remix paths'],
    engine: {
      zone: 'arcade-worlds',
      portalType: 'game-gate',
      spawn: { x: 67, y: 53, z: 0 },
      camera: 'arcade-gate-dolly',
      travelLine: 'play-bridge',
      futureSystems: ['avatar-control', 'world-select', 'matchmaking-lobby', 'limited-skin-loadouts', 'player clubs'],
    },
  },
  {
    id: 'studio',
    name: 'STATIC Studio',
    eyebrow: 'Creation Tower',
    route: '/studio',
    hotspotClass: 'district-hotspot--studio',
    status: 'Creator bays open',
    metric: 'Build floor',
    copy: 'The backstage command center for Entities, shows, Signals, PLAY concepts, drops, worlds, and future provider workflows.',
    unlocks: ['Entity tools', 'Project saves', 'Release planning'],
    engine: {
      zone: 'creation-tower',
      portalType: 'creator-workspace',
      spawn: { x: 29, y: 20, z: 0 },
      camera: 'tower-elevator-rise',
      travelLine: 'studio-elevator',
      futureSystems: ['creator-bays', 'provider-job-board', 'asset-review-room', 'creator business headquarters'],
    },
  },
  {
    id: 'channels',
    name: 'Channels',
    eyebrow: 'Creator Venues',
    route: '/channels',
    hotspotClass: 'district-hotspot--channels',
    status: 'Venues online',
    metric: 'Owned worlds',
    copy: 'Profiles become destinations: feed, video, live status, music, drops, worlds, lore, and audience return loops.',
    unlocks: ['Venue pages', 'Follow graph', 'Pinned Signals'],
    engine: {
      zone: 'creator-venues',
      portalType: 'owned-channel',
      spawn: { x: 52, y: 17, z: 0 },
      camera: 'creator-row-orbit',
      travelLine: 'venue-row',
      futureSystems: ['public-channel-rooms', 'creator-npc-hosts', 'fan-wall', 'venue-heat', 'creator-owned properties'],
    },
  },
  {
    id: 'radio',
    name: 'Radio',
    eyebrow: 'Rooftop Frequency',
    route: '/radio',
    hotspotClass: 'district-hotspot--radio',
    status: 'On air',
    metric: 'Station row',
    copy: 'Always-on station previews, moods, artist takeovers, cultural programming, and future AI-powered radio systems.',
    unlocks: ['Station saves', 'Program reminders', 'Audio mood layer'],
    engine: {
      zone: 'rooftop-frequency',
      portalType: 'audio-venue',
      spawn: { x: 42, y: 57, z: 0 },
      camera: 'rooftop-frequency-rise',
      travelLine: 'roof-access',
      futureSystems: ['spatial-audio', 'station-hosts', 'music-rights-gate', 'event-simulcast'],
    },
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    eyebrow: 'Asset Boulevard',
    route: '/marketplace',
    hotspotClass: 'district-hotspot--marketplace',
    status: 'Preview drops live',
    metric: 'Owned culture',
    copy: 'Digital drops, templates, skins, memberships, assets, and creator access signals become inventory intent.',
    unlocks: ['Save drops', 'Request access', 'Future transactions'],
    engine: {
      zone: 'asset-boulevard',
      portalType: 'commerce-preview',
      spawn: { x: 88, y: 64, z: 0 },
      camera: 'market-row-track',
      travelLine: 'asset-boulevard',
      futureSystems: ['drop-cases', 'wallet-gate', 'membership-door', 'property deed previews'],
    },
  },
  {
    id: 'sage',
    name: 'S.A.G.E.',
    eyebrow: 'Concierge Signal',
    route: '/sage',
    hotspotClass: 'district-hotspot--sage',
    status: 'Guide online',
    metric: 'Operator layer',
    copy: 'Ask the network concierge to explain what is live, what is preview, where to go, and what to build next.',
    unlocks: ['Guided tour', 'City OS help', 'Command panel'],
    engine: {
      zone: 'sage-concierge',
      portalType: 'assistant-presence',
      spawn: { x: 27, y: 74, z: 0 },
      camera: 'concierge-platform',
      travelLine: 'sage-platform',
      futureSystems: ['full-body-guide', 'voice-presence', 'tour-pathfinding'],
    },
  },
]

export const districtPropertyLayer = [
  {
    id: 'sky-penthouse-row',
    name: 'Sky Penthouse Row',
    type: 'Personal Residence',
    tier: 'crown-ridge',
    status: 'planned',
    copy: 'High-rise homes for Entities, creators, collectors, and teams with invite-only rooms, display walls, and private spawn points.',
    engine: { spawn: { x: 78, y: 16, z: 0 }, elevation: 3.6, footprint: 'vertical-luxury' },
  },
  {
    id: 'creator-business-strip',
    name: 'Creator Business Strip',
    type: 'Public Business',
    tier: 'base-loop',
    status: 'planned',
    copy: 'A place for creators to own browsable storefronts, studios, lounges, galleries, clinics, clubs, agencies, or branded headquarters.',
    engine: { spawn: { x: 36, y: 44, z: 0 }, elevation: 1.2, footprint: 'street-facing' },
  },
  {
    id: 'estate-hills',
    name: 'Estate Hills',
    type: 'Mansions / Castles',
    tier: 'crown-ridge',
    status: 'planned',
    copy: 'Prestige residences overlooking the district for major Entities, studios, founders, and lore-heavy characters.',
    engine: { spawn: { x: 17, y: 18, z: 0 }, elevation: 4.2, footprint: 'prestige-residence' },
  },
  {
    id: 'hilltop-casino-hotel',
    name: 'Hilltop Casino Hotel',
    type: 'Landmark Spawn',
    tier: 'summit-tower',
    status: 'planned',
    copy: 'A high-status landmark concept for a character, founder, studio, or faction that spawns above the city and pulls visitors uphill.',
    engine: { spawn: { x: 91, y: 12, z: 0 }, elevation: 5.4, footprint: 'landmark-venue' },
  },
]

export const venueTravelScript = {
  signals: 'Routing through Discovery Boulevard. Public culture pulse ahead.',
  live: 'Crossing the broadcast line. Arena rooms are warming.',
  play: 'Approaching Arcade Worlds. Prompt engines online.',
  studio: 'Ascending to Creation Tower. Studio bays opening.',
  channels: 'Entering Creator Venues. Owned worlds coming into range.',
  radio: 'Rooftop frequency locked. Station row is on air.',
  marketplace: 'Asset Boulevard ahead. Drops and passes loading.',
}

export const worldEngineReadiness = [
  ['Scene manifest', 'Venue IDs, routes, spawn points, camera intents, travel lines, and future systems are centralized.'],
  ['Engine-ready foundation', 'The Arrival District is structured so a real engine layer can take over movement, camera paths, venue selection, travel, and world state later.'],
  ['Travel contract', 'Current cinematic travel can be replaced by engine camera paths, vehicle paths, or avatar movement without changing route behavior.'],
  ['S.A.G.E. contract', 'The guide remains a clicked interaction layer, ready to become a full-body in-world presence later.'],
  ['Live venue gravity', 'The manifest now anticipates entity concerts, crowd rushes, event drops, simulcasts, and Signals aftershock loops.'],
  ['Property layer', 'Residences, penthouses, creator businesses, mansions, castles, and landmark spawn venues are planned as real ownership systems, not fake storefronts.'],
  ['Vertical city', 'The city is planned as a mountain hierarchy: darker street pulse at the base, Tunnel Rise suburbia after the freeway tunnel, Crown Ridge luxury above, and STATIC Tower at the summit.'],
  ['Create-a-player', 'The next avatar system needs identity sculpting, wardrobe, rigging, spawn ownership, inventory, and persistence before it becomes true gameplay.'],
]

export function getDistrictVenue(id) {
  return districtVenues.find((venue) => venue.id === id) || districtVenues[0]
}
