export const worldEngineStatus = {
  mode: 'web-preview',
  engine: 'not-mounted',
  version: '0.1.0',
  sceneId: 'static-arrival-district',
  copy: 'The public site is prepared for a future real-time world engine, but no multiplayer, NPC, avatar-control, or paid generation system is active in this build.',
}

export const arrivalCinemaClips = [
  {
    id: 'arrival-walk-01',
    src: '/assets/videos/static-arrival-walk-01.mov',
    label: 'ARRIVAL WALK // 01',
    caption: 'The city opens. Venues light up. STATIC becomes a place.',
    cameraIntent: 'establishing-approach',
  },
  {
    id: 'arrival-walk-02',
    src: '/assets/videos/static-arrival-walk-02.mov',
    label: 'ARRIVAL WALK // 02',
    caption: 'Move through the district before the interface appears.',
    cameraIntent: 'street-level-arrival',
  },
]

export const districtVenues = [
  {
    id: 'signals',
    name: 'Signals',
    eyebrow: 'Discovery Boulevard',
    route: '/signals',
    hotspotClass: 'district-hotspot--signals',
    status: 'Culture feed live',
    metric: 'Public pulse',
    copy: 'Short-form drops, creator posts, premieres, clips, releases, and strange new worlds move through this boulevard first.',
    unlocks: ['For-you discovery', 'Public cloud Signals', 'Creator drops'],
    engine: {
      zone: 'discovery-boulevard',
      portalType: 'social-feed',
      spawn: { x: 55, y: 37, z: 0 },
      camera: 'street-feed-pan',
      travelLine: 'north-east-boulevard',
      futureSystems: ['live-feed-panels', 'creator-crowd', 'personalized-billboards'],
    },
  },
  {
    id: 'live',
    name: 'STATIC LIVE',
    eyebrow: 'Broadcast Arena',
    route: '/live',
    hotspotClass: 'district-hotspot--live',
    status: 'Rooms warming',
    metric: 'Live floor',
    copy: 'Premieres, watch parties, creator rooms, entity broadcasts, performances, and audience-driven events gather here.',
    unlocks: ['Premiere rooms', 'Entity live mode', 'Event countdowns'],
    engine: {
      zone: 'broadcast-arena',
      portalType: 'event-venue',
      spawn: { x: 72, y: 28, z: 0 },
      camera: 'arena-marquee-push',
      travelLine: 'broadcast-line',
      futureSystems: ['live-stage-presence', 'watch-party-crowds', 'event-ticketing-gate'],
    },
  },
  {
    id: 'play',
    name: 'STATIC PLAY',
    eyebrow: 'Arcade Worlds',
    route: '/play',
    hotspotClass: 'district-hotspot--play',
    status: 'Prompt engine ready',
    metric: 'Playable ideas',
    copy: 'Describe a game or interactive world, then move from idea to saved concept without leaving the network.',
    unlocks: ['Prompt UI', 'World cards', 'Remix paths'],
    engine: {
      zone: 'arcade-worlds',
      portalType: 'game-gate',
      spawn: { x: 67, y: 53, z: 0 },
      camera: 'arcade-gate-dolly',
      travelLine: 'play-bridge',
      futureSystems: ['avatar-control', 'world-select', 'matchmaking-lobby'],
    },
  },
  {
    id: 'studio',
    name: 'STATIC Studio',
    eyebrow: 'Creation Tower',
    route: '/studio',
    hotspotClass: 'district-hotspot--studio',
    status: 'Creator bays open',
    metric: 'Build floor',
    copy: 'The backstage command center for Entities, shows, Signals, PLAY concepts, drops, worlds, and future provider workflows.',
    unlocks: ['Entity tools', 'Project saves', 'Release planning'],
    engine: {
      zone: 'creation-tower',
      portalType: 'creator-workspace',
      spawn: { x: 29, y: 20, z: 0 },
      camera: 'tower-elevator-rise',
      travelLine: 'studio-elevator',
      futureSystems: ['creator-bays', 'provider-job-board', 'asset-review-room'],
    },
  },
  {
    id: 'channels',
    name: 'Channels',
    eyebrow: 'Creator Venues',
    route: '/channels',
    hotspotClass: 'district-hotspot--channels',
    status: 'Venues online',
    metric: 'Owned worlds',
    copy: 'Profiles become destinations: feed, video, live status, music, drops, worlds, lore, and audience return loops.',
    unlocks: ['Venue pages', 'Follow graph', 'Pinned Signals'],
    engine: {
      zone: 'creator-venues',
      portalType: 'owned-channel',
      spawn: { x: 52, y: 17, z: 0 },
      camera: 'creator-row-orbit',
      travelLine: 'venue-row',
      futureSystems: ['public-channel-rooms', 'creator-npc-hosts', 'fan-wall'],
    },
  },
  {
    id: 'radio',
    name: 'Radio',
    eyebrow: 'Rooftop Frequency',
    route: '/radio',
    hotspotClass: 'district-hotspot--radio',
    status: 'On air',
    metric: 'Station row',
    copy: 'Always-on station previews, moods, artist takeovers, cultural programming, and future AI-powered radio systems.',
    unlocks: ['Station saves', 'Program reminders', 'Audio mood layer'],
    engine: {
      zone: 'rooftop-frequency',
      portalType: 'audio-venue',
      spawn: { x: 42, y: 57, z: 0 },
      camera: 'rooftop-frequency-rise',
      travelLine: 'roof-access',
      futureSystems: ['spatial-audio', 'station-hosts', 'music-rights-gate'],
    },
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    eyebrow: 'Asset Boulevard',
    route: '/marketplace',
    hotspotClass: 'district-hotspot--marketplace',
    status: 'Preview drops live',
    metric: 'Owned culture',
    copy: 'Digital drops, templates, skins, memberships, assets, and creator access signals become inventory intent.',
    unlocks: ['Save drops', 'Request access', 'Future transactions'],
    engine: {
      zone: 'asset-boulevard',
      portalType: 'commerce-preview',
      spawn: { x: 88, y: 64, z: 0 },
      camera: 'market-row-track',
      travelLine: 'asset-boulevard',
      futureSystems: ['drop-cases', 'wallet-gate', 'membership-door'],
    },
  },
  {
    id: 'sage',
    name: 'S.A.G.E.',
    eyebrow: 'Concierge Signal',
    route: '/sage',
    hotspotClass: 'district-hotspot--sage',
    status: 'Guide online',
    metric: 'Operator layer',
    copy: 'Ask the network concierge to explain what is live, what is preview, where to go, and what to build next.',
    unlocks: ['Guided tour', 'District OS help', 'Command panel'],
    engine: {
      zone: 'sage-concierge',
      portalType: 'assistant-presence',
      spawn: { x: 27, y: 74, z: 0 },
      camera: 'concierge-platform',
      travelLine: 'sage-platform',
      futureSystems: ['full-body-guide', 'voice-presence', 'tour-pathfinding'],
    },
  },
]

export const venueTravelScript = {
  signals: 'Routing through Discovery Boulevard. Public culture pulse ahead.',
  live: 'Crossing the broadcast line. Arena rooms are warming.',
  play: 'Approaching Arcade Worlds. Prompt engines online.',
  studio: 'Ascending to Creation Tower. Studio bays opening.',
  channels: 'Entering Creator Venues. Owned worlds coming into range.',
  radio: 'Rooftop frequency locked. Station row is on air.',
  marketplace: 'Asset Boulevard ahead. Drops and passes loading.',
}

export const worldEngineReadiness = [
  ['Scene manifest', 'Venue IDs, routes, spawn points, camera intents, travel lines, and future systems are centralized.'],
  ['Engine mount', 'The Arrival District exposes a stable DOM mount and data attributes for a future real-time scene.'],
  ['Travel contract', 'Current cinematic travel can be replaced by engine camera paths without changing route behavior.'],
  ['S.A.G.E. contract', 'The guide remains a clicked interaction layer, ready to become a full-body in-world presence later.'],
]

export function getDistrictVenue(id) {
  return districtVenues.find((venue) => venue.id === id) || districtVenues[0]
}
