export const staticCityWorld = {
  name: 'STATIC City',
  access: 'owner-only-build',
  principle: 'Unreal Engine 5.8 game-first world layer with social media interfaces, not a website with game controls.',
  currentSlice: 'Browser owner prototype route: STATIC Tower command suite -> valet -> luxury SUV -> Market Walk -> Radio Rooftop VIP -> vibe-mode strip cruise -> tower return. Full canon moves Mr. Stone primary residence to Private STATIC Island.',
}

export const staticCityPlatformDoors = [
  ['Web / PWA', 'Public command center: STATIC ID, Signals, access requests, profile, Entity management, social graph, creator pages, waitlist, public lore, and lightweight city preview.'],
  ['iPhone / Android app', 'Native social/creator companion: push notifications, camera/mic capture, Signals, Radio, companion/inventory management, chat, events, and travel handoff.'],
  ['PC / Steam client', 'Primary high-fidelity city client: Unreal Engine 5.8 vertical slice, avatar control, vehicles, venues, spatial audio, multiplayer rooms, and creator/game systems.'],
  ['Console client', 'Living-room version after PC proves the loop: controller-first traversal, optimized UI, multiplayer events, account sync, store compliance, and performance budgets.'],
  ['Steam Deck / handheld PC', 'Track as a handheld target after the UE5.8 vertical slice proves controller input, readable UI, cloud saves, performance, and battery-safe settings.'],
  ['SteamVR / VR hardware', 'Future immersion layer: headset mode, spatial interaction, premium venue experiences, haptic suits, treadmills, and room-scale events after core gameplay is proven.'],
]

export const staticCityExecutionPath = [
  ['01', 'STATIC ID', 'One account owns profile, Entity, inventory, companions, vehicles, properties, Signals, Radio, and event access across every client.'],
  ['02', 'Persistent Entity', 'Save actual Entity identity, body/style, wardrobe, loadout, spawn point, and privacy/moderation state.'],
  ['03', 'Web/PWA control layer', 'Keep the public web and app shell fast, shareable, and social while heavier gameplay moves into a game client.'],
  ['04', 'UE5.8 vertical slice', 'Build Arrival District, Private STATIC Island, Mr. Stone, tower command suite, valet, SUV, Market Walk, STATIC Arena, Club STATIC, Radio Rooftop, Vibe Mode, marina, and guardian squad as the proof slice.'],
  ['05', 'Shared backend contracts', 'Unreal, web, mobile, and future console clients read/write the same Supabase-owned account state.'],
  ['06', 'Signals social layer', 'Turn posts into city billboards, phone clips, crowd heat, follows, saves, comments, and event aftershock.'],
  ['07', 'Studio / PLAY tools', 'Creator production tools feed worlds, shows, games, Entity media, and venue programming back into the city.'],
  ['08', 'Radio / Live gravity', 'Radio, concerts, premieres, rooftop sessions, and live events create movement across the city.'],
  ['09', 'Scarcity and status', 'Beta access, properties, vehicles, companions, wardrobe, and event passes become visible progression without fake payments.'],
  ['10', 'Hardware expansion', 'VR, haptics, treadmills, console, and premium installations come after the core account/game/social loop works.'],
]

export const staticCityGuardianSquad = [
  {
    id: 'obsidian-crown-dragon',
    name: 'Obsidian Crown Dragon',
    type: 'mythic dragon',
    scaleClass: 'colossal',
    role: 'Rideable perimeter guardian',
    slot: 'mount',
    behavior: 'Follows outside, circles vehicles, becomes rideable after the real engine has mount traversal.',
    protectMode: 'permission perimeter / opt-in mode only',
    assetTarget: '/assets/world/city/companions/dragon-companion.glb',
    color: '#9d63ff',
    accent: '#72ffba',
    offset: { x: -1.9, y: 0.24, z: 1.18 },
    indoorMode: 'perimeter',
  },
  {
    id: 'monarch-robot-guard',
    name: 'Monarch Guard Unit',
    type: 'robot bodyguard',
    scaleClass: 'large',
    role: 'Close-protection bodyguard',
    slot: 'bodyguard-01',
    behavior: 'Walks near Mr. Stone, blocks approach lanes visually, and becomes real protection only inside validated game modes.',
    protectMode: 'visual follow now / server-validated later',
    assetTarget: '/assets/world/city/companions/robot-bodyguard.glb',
    color: '#55ddff',
    accent: '#fff0ca',
    offset: { x: 1.22, y: 0.08, z: 0.78 },
    indoorMode: 'active',
  },
  {
    id: 'sagefire-wizard',
    name: 'Sagefire Wizard',
    type: 'feminine wizard companion',
    scaleClass: 'small',
    role: 'Signal-mage guide and ward caster',
    slot: 'companion-01',
    behavior: 'Floats near Mr. Stone, reads as S.A.G.E.-adjacent magic, and triggers non-gory banish/deny animations in protected spaces later.',
    protectMode: 'ward visual now / opt-in banish animation later',
    assetTarget: '/assets/world/city/companions/cute-companion.glb',
    color: '#e56cff',
    accent: '#fff8ef',
    offset: { x: 0.72, y: 0.86, z: -0.86 },
    indoorMode: 'active',
  },
]

export const staticCityImageRead = [
  ['Sports arena', 'The crowd jerseys, arena-night energy, and packed district plaza say STATIC needs a sports venue where basketball is the first playable proof.'],
  ['VIP strip tables', 'People seated in the middle of the city makes nightlife and status visible: tables, bottle service, cigar/drink props, and social access tiers.'],
  ['Club STATIC', 'The strip needs an actual nightlife destination where Entities can party, perform, host afterparties, and move from Signals into real venues.'],
  ['Music venue gravity', 'The background stages and signage make Radio, live sessions, concerts, and red-carpet events feel like places you travel to, not tabs.'],
  ['Billboard economy', 'Every building face can become a creator post, sports promo, event ad, drop wall, Radio signal, or venue announcement once moderation exists.'],
  ['Street-level social proof', 'Fans, phones, cars, guards, and clusters of people make the district feel alive before multiplayer arrives; NPC shells and crowd loops matter.'],
  ['Luxury status climb', 'The glossy black wardrobe, wet pavement, towers, VIP signage, and premium architecture are the exact status language for properties, vehicles, and wardrobe.'],
  ['Full-city scale', 'The image is one district, not the whole world. UE5.8/PCG lets STATIC expand into beaches, suburbs, marina routes, island estates, sports, nightlife, and mountain landmarks.'],
]

export const staticCityTiers = [
  {
    id: 'summit',
    name: 'STATIC Tower Summit',
    range: [0, 18],
    elevation: 'Summit',
    tone: 'gold',
    copy: 'The symbolic top: city command landmark, concert crown, theme park, observation deck, and celebrity red-carpet destination. Mr. Stone’s true residence moves to Private STATIC Island.',
  },
  {
    id: 'crown-ridge',
    name: 'Crown Ridge',
    range: [18, 38],
    elevation: 'Upper city',
    tone: 'champagne',
    copy: 'Luxury hotels, villas, elite lounges, galleries, high-status event routes, and prestige property approaches.',
  },
  {
    id: 'neon-rise',
    name: 'Neon Rise',
    range: [38, 58],
    elevation: 'Mid city',
    tone: 'violet',
    copy: 'Better apartments, Channels, studios, Radio approaches, PLAY lounges, nicer cars, and visible social status.',
  },
  {
    id: 'base-loop',
    name: 'Base Loop',
    range: [58, 78],
    elevation: 'Ring road',
    tone: 'purple',
    copy: 'The circular strip around the mountain: valet routes, Market Walk, starter businesses, transit, and public venue access.',
  },
  {
    id: 'street-pulse',
    name: 'Street Pulse',
    range: [78, 100],
    elevation: 'Base',
    tone: 'street',
    copy: 'Darker, louder, cheaper, crowded, accessible, and alive with creator hustle, open Signals, street music, and first homes.',
  },
]

export const staticCityRouteNodes = [
  {
    id: 'penthouse-spawn',
    label: 'Tower Command Suite',
    type: 'property',
    tier: 'summit',
    x: 55,
    y: 8,
    status: 'top floor',
    objective: 'Prototype wake route in the STATIC Tower command suite. Full canon starts from Mr. Stone’s Private STATIC Island estate once the UE5.8 world exists.',
    backend: 'profile, entity, property_access, inventory_state',
  },
  {
    id: 'penthouse-elevator',
    label: 'Penthouse Elevator',
    type: 'travel',
    tier: 'summit',
    x: 57,
    y: 13,
    status: 'interior path',
    objective: 'Walk out of the penthouse and enter the private elevator down to the tower valet floor.',
    backend: 'interior_route_state, elevator_jobs, access_rules',
  },
  {
    id: 'static-tower',
    label: 'STATIC Tower',
    type: 'landmark',
    tier: 'summit',
    x: 52,
    y: 10,
    status: 'canon locked',
    objective: 'Anchor the city with the flagship venue, event crown, theme park, and command view.',
    backend: 'landmarks, events, access_rules',
  },
  {
    id: 'summit-valet',
    label: 'Tower Valet',
    type: 'travel',
    tier: 'crown-ridge',
    x: 60,
    y: 25,
    status: 'suv waiting',
    objective: 'Exit the elevator, wait for the luxury SUV, enter, and start STATIC Radio.',
    backend: 'vehicle_inventory, route_state, travel_jobs',
  },
  {
    id: 'crown-ridge',
    label: 'Crown Ridge',
    type: 'social',
    tier: 'crown-ridge',
    x: 42,
    y: 32,
    status: 'map shell',
    objective: 'Pass villas, hotels, elite lounges, red carpets, and high-status social architecture.',
    backend: 'presence, property_access, event_heat',
  },
  {
    id: 'neon-drive',
    label: 'Mountain Descent',
    type: 'route',
    tier: 'neon-rise',
    x: 54,
    y: 48,
    status: 'camera path next',
    objective: 'Cruise through brighter mid-city roads while Radio and billboards react to live events.',
    backend: 'route_state, radio_session, billboard_queue',
  },
  {
    id: 'radio-building',
    label: 'Radio Building',
    type: 'venue',
    tier: 'neon-rise',
    x: 62,
    y: 54,
    status: 'arrival',
    objective: 'Pull up to the STATIC Radio building, step out, walk in, and take the elevator to the rooftop party.',
    backend: 'venue_arrivals, elevator_jobs, valet_dropoffs',
  },
  {
    id: 'play-gate',
    label: 'PLAY Gate',
    type: 'venue',
    tier: 'neon-rise',
    x: 73,
    y: 52,
    status: 'venue shell',
    objective: 'Enter playable worlds, limited modes, creator arenas, and future generated game sessions.',
    backend: 'play_sessions, world_templates, moderation',
  },
  {
    id: 'static-arena',
    label: 'STATIC Arena',
    type: 'sport',
    tier: 'neon-rise',
    x: 47,
    y: 53,
    status: 'basketball first',
    objective: 'Basketball becomes the first sports proof: arena nights, fan heat, VIP boxes, creator teams, and later playable 1v1/3v3/5v5.',
    backend: 'sports_events, arena_sessions, team_rosters, event_access',
  },
  {
    id: 'club-static',
    label: 'Club STATIC',
    type: 'nightlife',
    tier: 'base-loop',
    x: 66,
    y: 65,
    status: 'nightlife',
    objective: 'Party, aftershows, sports watch parties, creator appearances, VIP tables, and social gravity on the strip.',
    backend: 'events, venue_access, presence_events, live_rooms',
  },
  {
    id: 'market-walk',
    label: 'Market Walk',
    type: 'market',
    tier: 'base-loop',
    x: 43,
    y: 66,
    status: 'fit upgrade',
    objective: 'Stop at the mall, buy new clothes and jewelry, update outfit/status, then continue to STATIC Radio.',
    backend: 'items, wishlists, entitlements, payments_later',
  },
  {
    id: 'radio-rooftop',
    label: 'Radio Rooftop VIP',
    type: 'event',
    tier: 'neon-rise',
    x: 58,
    y: 61,
    status: 'vip escort',
    objective: 'Get escorted to VIP, receive a drink and cigar, and sit on the couch while the rooftop party moves around him.',
    backend: 'stations, rights, audio_sessions, venue_presence',
  },
  {
    id: 'vibe-strip',
    label: 'Vibe Mode Strip',
    type: 'route',
    tier: 'street-pulse',
    x: 32,
    y: 82,
    status: 'first person',
    objective: 'Roll the window down, switch to first-person camera, and cruise past STATIC Strip skyscrapers while STATIC Blues plays.',
    backend: 'camera_mode, radio_session, route_state, ambient_city_audio',
  },
  {
    id: 'signal-strip',
    label: 'Signal Strip',
    type: 'social',
    tier: 'street-pulse',
    x: 31,
    y: 84,
    status: 'feed bridge',
    objective: 'Open Signals, follow Entities, discover drops, watch clips, and return to the city loop.',
    backend: 'signals, follows, comments, content_moderation',
  },
  {
    id: 'the-red-light',
    label: 'The Red Light',
    type: 'hidden-nightlife',
    tier: 'street-pulse',
    x: 28,
    y: 86,
    status: 'hidden entrance',
    objective: 'Find the tucked-away bar, enter through the front, cross the interior, and exit through the back into the secret mature-nightlife walking street.',
    backend: 'age_gate_later, venue_access, discovery_flags, moderation, presence_events',
  },
  {
    id: 'hidden-walking-street',
    label: 'Hidden Walking Street',
    type: 'hidden-nightlife',
    tier: 'street-pulse',
    x: 24,
    y: 88,
    status: 'secret corridor',
    objective: 'Prototype the dense neon walking-street energy: bars, lounges, performer balconies, food stalls, coded doors, VIP stairways, crowd heat, and rain-reflection spectacle.',
    backend: 'age_gate_later, venue_access, npc_crowds, events, moderation, discovery_flags',
  },
  {
    id: 'velocity-garage',
    label: 'Velocity Garage',
    type: 'vehicle',
    tier: 'street-pulse',
    x: 37,
    y: 78,
    status: 'custom shop',
    objective: 'Build the garage identity loop: paint, rims, underglow, suspension, interior, audio, wraps, and saved vehicle builds.',
    backend: 'vehicle_builds, inventory_items, entitlements, moderation',
  },
  {
    id: 'night-run-light',
    label: 'Night Run Light',
    type: 'race',
    tier: 'street-pulse',
    x: 27,
    y: 87,
    status: 'red-light race',
    objective: 'Prototype red-light challenges where an NPC or future real player pulls up beside you and launches an instanced race route.',
    backend: 'race_sessions, route_sessions, non_cash_signal_credits, anti_cheat_later',
  },
  {
    id: 'car-show-plaza',
    label: 'Car Show Plaza',
    type: 'event',
    tier: 'base-loop',
    x: 48,
    y: 70,
    status: 'feed event',
    objective: 'Host car shows promoted through Signals with custom cars, lowriders, slabs, lifted trucks, bikes, motorcycles, stage performances, clips, and drops.',
    backend: 'events, signals_social, vehicle_builds, presence_events, moderation',
  },
  {
    id: 'takeover-zone',
    label: 'Takeover Zone',
    type: 'race',
    tier: 'street-pulse',
    x: 22,
    y: 91,
    status: 'limited-time',
    objective: 'Controlled fictional underground zone for donuts, burnout choreography, passenger-camera shots, crowd heat, and replay clips.',
    backend: 'events, route_sessions, replay_clips, safety_rules, moderation',
  },
  {
    id: 'companion-hub',
    label: 'Companion Hub',
    type: 'companion',
    tier: 'base-loop',
    x: 72,
    y: 68,
    status: 'guardian select',
    objective: 'Choose cute sidekicks, guardian bodyguards, robots, creatures, dragons, golems, companion stance, follow distance, and loadout slots.',
    backend: 'companions, companion_slots, inventory_items, moderation',
  },
  {
    id: 'guardian-yard',
    label: 'Guardian Yard',
    type: 'companion',
    tier: 'neon-rise',
    x: 76,
    y: 58,
    status: 'bodyguard test',
    objective: 'Prototype guardian follow/protect behavior for opt-in danger modes, crew zones, faction arenas, and high-status owner entrances.',
    backend: 'companions, companion_behavior, conflict_sessions, safety_rules',
  },
  {
    id: 'crew-hq',
    label: 'Crew HQ',
    type: 'crew',
    tier: 'base-loop',
    x: 64,
    y: 74,
    status: 'faction base',
    objective: 'Prototype crew formation, crew identity, roles, banners, home base, and moderated faction presence.',
    backend: 'crews, crew_memberships, moderation, presence_events',
  },
  {
    id: 'dominion-arena',
    label: 'Dominion Arena',
    type: 'conflict',
    tier: 'street-pulse',
    x: 18,
    y: 82,
    status: 'opt-in war mode',
    objective: 'Prototype instanced crew-versus-crew spectacle with fictional loadouts, territory prestige, non-cash Signal Credits, and no public real-value wagering.',
    backend: 'conflict_sessions, territory_control, signal_credit_ledger, anti_cheat_later, moderation',
  },
  {
    id: 'fortress-row',
    label: 'Fortress Row',
    type: 'crew',
    tier: 'neon-rise',
    x: 69,
    y: 57,
    status: 'upgrade lane',
    objective: 'Prototype district upgrades: walls, gates, shields, turrets, watch decks, command rooms, and treaty-bloc visual control.',
    backend: 'territory_control, fortress_upgrades, crews, entitlements, moderation',
  },
  {
    id: 'survival-zone',
    label: 'Survival Zone',
    type: 'conflict',
    tier: 'street-pulse',
    x: 16,
    y: 92,
    status: 'wave event',
    objective: 'Prototype wave-defense events where crews defend against fictional NPC waves in first-person or third-person arcade mode.',
    backend: 'survival_sessions, npc_waves, replay_clips, rewards_non_cash, moderation',
  },
  {
    id: 'tower-return',
    label: 'Tower Return',
    type: 'property',
    tier: 'summit',
    x: 52,
    y: 12,
    status: 'valet tip',
    objective: 'Third-person far shot of the SUV going back up the mountain, then Mr. Stone gets out, tips valet, and walks back in.',
    backend: 'route_completion, npc_interaction, property_spawn_return',
  },
]

export const mrStoneOpeningMission = {
  id: 'mr-stone-opening-night',
  title: 'Mr. Stone: Owner Storyboard Route',
  subtitle: 'Prototype path from penthouse to Market Walk, Radio Rooftop, Vibe Mode, and return.',
  lead: 'This is an optional owner-only browser slice, not the final home canon. It proves STATIC City systems can carry a cinematic open-world route while the UE5.8 build expands toward Private STATIC Island, beaches, marina, suburbs, and full districts.',
  character: {
    name: 'Mr. Stone',
    role: 'STATIC founder / tower owner',
    spawn: 'Prototype: STATIC Tower command suite. Full canon: Private STATIC Island estate.',
    vehicle: 'Black luxury SUV',
    radio: 'STATIC Blues',
  },
  flags: [
    'owner-only',
    'storyboard-only',
    'authored cinematic loop',
    'no real animation yet',
    'no licensed music yet',
    'backend contracts only',
  ],
}

export const staticCitySceneModes = {
  penthouse: {
    id: 'penthouse',
    label: 'Penthouse interior',
    camera: 'third-person follow',
    control: 'local avatar controller',
    step: 1.65,
    bounds: { x: [51, 59], y: [5, 15] },
    copy: 'The first playable scene starts inside Mr. Stone’s top-floor penthouse: glass skyline wall, wardrobe/status area, private hallway, and elevator target.',
  },
  valet: {
    id: 'valet',
    label: 'Tower valet floor',
    camera: 'cinematic third-person',
    control: 'guided interaction',
    step: 2.2,
    bounds: { x: [55, 63], y: [20, 29] },
    copy: 'The first exterior-interior bridge: elevator opens to valet, SUV arrives, radio state starts, and NPC valet logic will live here later.',
  },
  vehicle: {
    id: 'vehicle',
    label: 'Vehicle route',
    camera: 'authored chase cam',
    control: 'cinematic travel first',
    step: 3,
    bounds: { x: [28, 70], y: [24, 84] },
    copy: 'Vehicle movement is still authored. Real driving comes after avatar, camera, route, and scene streaming foundations are stable.',
  },
  market: {
    id: 'market',
    label: 'Market Walk retail',
    camera: 'shopping third-person',
    control: 'guided shopping interaction',
    step: 2,
    bounds: { x: [39, 47], y: [62, 69] },
    copy: 'Market Walk proves the fit, jewelry, inventory, and status loop before the Radio Rooftop arrival.',
  },
  venue: {
    id: 'venue',
    label: 'Venue approach',
    camera: 'social third-person',
    control: 'guided avatar interaction',
    step: 2.4,
    bounds: { x: [54, 66], y: [50, 65] },
    copy: 'Venue spaces are where NPCs, crowds, props, music, access, and social presence start becoming gameplay.',
  },
  city: {
    id: 'city',
    label: 'STATIC City exterior',
    camera: 'world map prototype',
    control: 'route node movement',
    step: 3,
    bounds: { x: [4, 96], y: [4, 96] },
    copy: 'The broad city layer remains a world map shell until we have authored street chunks, avatar traversal, vehicles, and optimization.',
  },
}

export const staticCityOpeningSequence = [
  {
    id: 'wake-room',
    label: 'Wake at skyline glass',
    beatId: 'wake',
    position: { x: 55, y: 8 },
    facing: Math.PI,
    motion: 'idle',
    duration: 900,
    cue: 'Penthouse lights rise. STATIC Tower hum comes online.',
  },
  {
    id: 'wardrobe-check',
    label: 'Status wall check',
    beatId: 'wake',
    position: { x: 53.8, y: 9.7 },
    facing: Math.PI * 0.74,
    motion: 'walking',
    duration: 1200,
    cue: 'Mr. Stone crosses to the wardrobe/status wall before the route loads.',
  },
  {
    id: 'hallway-step',
    label: 'Private hallway',
    beatId: 'walk-to-elevator',
    position: { x: 55.7, y: 11.2 },
    facing: Math.PI * 0.18,
    motion: 'walking',
    duration: 1300,
    cue: 'Camera follows behind. Glass reflections fall away into gold hallway light.',
  },
  {
    id: 'elevator-call',
    label: 'Call private elevator',
    beatId: 'walk-to-elevator',
    position: { x: 57, y: 13 },
    facing: 0,
    motion: 'idle',
    duration: 900,
    cue: 'Elevator panel responds. Valet floor confirms the SUV is waiting.',
  },
  {
    id: 'elevator-open',
    label: 'Elevator opens',
    beatId: 'walk-to-elevator',
    position: { x: 57, y: 13 },
    facing: 0,
    motion: 'idle',
    doorOpen: true,
    duration: 1000,
    cue: 'Doors open into warm tower light. The interior scene hands off to valet.',
  },
  {
    id: 'valet-transition',
    label: 'Arrive at valet floor',
    beatId: 'valet',
    position: { x: 60, y: 25 },
    facing: Math.PI * 0.1,
    motion: 'idle',
    duration: 900,
    cue: 'Scene transition: valet level, black SUV, STATIC Radio boot cue.',
  },
]

export const staticCityValetSequence = [
  {
    id: 'valet-arrival',
    label: 'Elevator to valet floor',
    beatId: 'valet',
    position: { x: 60, y: 25 },
    facing: Math.PI * 0.12,
    motion: 'idle',
    duration: 900,
    cue: 'Elevator opens to the tower valet level. Gold light hits the black floor.',
  },
  {
    id: 'valet-signal',
    label: 'Valet receives signal',
    beatId: 'valet',
    position: { x: 60, y: 25 },
    facing: Math.PI * 0.22,
    motion: 'idle',
    duration: 900,
    cue: 'Valet confirms Mr. Stone. The SUV route lights up and the vehicle approaches.',
    vehicleApproach: true,
    vehicleOffset: { x: -1.15, z: 1.15 },
  },
  {
    id: 'suv-pulls-in',
    label: 'Black SUV pulls in',
    beatId: 'valet',
    position: { x: 59.4, y: 25.8 },
    facing: Math.PI * 0.44,
    motion: 'walking',
    duration: 1300,
    cue: 'The black luxury SUV rolls into position. STATIC trim and cabin glow come alive.',
    vehicleApproach: true,
    vehicleOffset: { x: -0.82, z: 0.72 },
  },
  {
    id: 'door-opens',
    label: 'SUV door opens',
    beatId: 'valet',
    position: { x: 59.4, y: 25.8 },
    facing: Math.PI * 0.44,
    motion: 'idle',
    duration: 1100,
    cue: 'Door opens. Interior radio panel boots with the STATIC Blues station cue.',
    vehicleDoorOpen: true,
    radioBoot: true,
    vehicleOffset: { x: -0.56, z: 0.58 },
  },
  {
    id: 'enter-suv',
    label: 'Enter SUV',
    beatId: 'valet',
    position: { x: 59.8, y: 26.2 },
    facing: Math.PI * 0.44,
    motion: 'walking',
    duration: 900,
    cue: 'Mr. Stone enters. Camera prepares to leave valet and hand off to the mountain descent.',
    vehicleDoorOpen: true,
    radioBoot: true,
    enteringVehicle: true,
    vehicleOffset: { x: -0.48, z: 0.48 },
  },
  {
    id: 'drive-handoff',
    label: 'Drive route armed',
    beatId: 'drive-to-radio',
    position: { x: 54, y: 48 },
    facing: -0.35,
    motion: 'idle',
    duration: 900,
    cue: 'STATIC Radio is live. The chase camera takes over for the drive toward Market Walk.',
    radioBoot: true,
    enteringVehicle: true,
  },
]

export const staticCityDriveSequence = [
  {
    id: 'drive-launch',
    label: 'Leave STATIC Tower',
    beatId: 'drive-to-radio',
    position: { x: 54, y: 48 },
    facing: -0.35,
    motion: 'driving',
    duration: 950,
    cue: 'SUV clears the tower valet. Chase camera locks. STATIC Radio keeps the route alive.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    vehicleOffset: { x: 0, z: 0 },
    routePulse: true,
    billboardSweep: true,
  },
  {
    id: 'neon-rise-descent',
    label: 'Neon Rise descent',
    beatId: 'drive-to-radio',
    position: { x: 50, y: 55 },
    facing: -0.42,
    motion: 'driving',
    duration: 1000,
    cue: 'The road drops through Neon Rise. Billboards react to Mr. Stone moving through the city.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    vehicleOffset: { x: 0, z: 0 },
    routePulse: true,
    billboardSweep: true,
  },
  {
    id: 'base-loop-merge',
    label: 'Base Loop merge',
    beatId: 'drive-to-radio',
    position: { x: 47, y: 61 },
    facing: -0.58,
    motion: 'driving',
    duration: 1000,
    cue: 'Traffic glow thickens near the Base Loop. Market Walk signage begins to pull focus.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    vehicleOffset: { x: 0, z: 0 },
    routePulse: true,
    billboardSweep: true,
  },
  {
    id: 'market-approach',
    label: 'Market Walk approach',
    beatId: 'mall-stop',
    position: { x: 43, y: 66 },
    facing: -0.68,
    motion: 'driving',
    duration: 1100,
    cue: 'Market Walk opens up ahead. Luxury retail lights hit the SUV paint.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    vehicleOffset: { x: 0, z: 0 },
    routePulse: true,
    billboardSweep: true,
    marketArrival: true,
  },
  {
    id: 'market-arrival',
    label: 'Arrive at Market Walk',
    beatId: 'mall-stop',
    position: { x: 43, y: 66 },
    facing: -0.68,
    motion: 'idle',
    duration: 900,
    cue: 'SUV stops at Market Walk. Next slice is exit vehicle, shop fit, jewelry, and status update.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    vehicleOffset: { x: 0, z: 0 },
    marketArrival: true,
  },
]

export const staticCityMarketSequence = [
  {
    id: 'market-door-open',
    label: 'Market curb stop',
    beatId: 'mall-stop',
    position: { x: 43, y: 66 },
    facing: -0.68,
    motion: 'idle',
    duration: 800,
    cue: 'SUV idles at Market Walk. Boutique lights and valet curb markers turn toward Mr. Stone.',
    radioBoot: true,
    vehicleDoorOpen: true,
    marketArrival: true,
    boutiqueLights: true,
    vehicleOffset: { x: 0.44, z: 0.48 },
  },
  {
    id: 'exit-suv',
    label: 'Step out',
    beatId: 'mall-stop',
    position: { x: 42.7, y: 65.7 },
    facing: -0.78,
    motion: 'walking',
    duration: 950,
    cue: 'Mr. Stone exits the SUV. Camera drops behind him for the retail walk-in.',
    radioBoot: true,
    vehicleDoorOpen: true,
    marketArrival: true,
    boutiqueLights: true,
    vehicleOffset: { x: 0.76, z: 0.62 },
  },
  {
    id: 'boutique-entry',
    label: 'Enter luxury floor',
    beatId: 'mall-stop',
    position: { x: 42.2, y: 64.8 },
    facing: -0.88,
    motion: 'walking',
    duration: 1100,
    cue: 'Glass doors open. Wardrobe wall, jewelry case, and status mirror come online.',
    marketArrival: true,
    boutiqueLights: true,
    marketInterior: true,
    vehicleOffset: { x: 1.18, z: 0.92 },
  },
  {
    id: 'fit-upgrade',
    label: 'Fit upgrade',
    beatId: 'mall-stop',
    position: { x: 42.2, y: 64.8 },
    facing: -0.88,
    motion: 'idle',
    duration: 1000,
    cue: 'Fit preview locks. Jacket trim and VIP status lighting update on the Entity.',
    marketArrival: true,
    boutiqueLights: true,
    marketInterior: true,
    outfitUpgrade: true,
    vehicleOffset: { x: 1.18, z: 0.92 },
  },
  {
    id: 'jewelry-lock',
    label: 'Jewelry lock',
    beatId: 'mall-stop',
    position: { x: 43.1, y: 65.3 },
    facing: -0.35,
    motion: 'walking',
    duration: 1100,
    cue: 'Jewelry case opens. Chain, watch, and status pass glow before rooftop access.',
    marketArrival: true,
    boutiqueLights: true,
    marketInterior: true,
    outfitUpgrade: true,
    jewelryUpgrade: true,
    vehicleOffset: { x: 0.96, z: 0.72 },
  },
  {
    id: 'status-confirm',
    label: 'Status confirmed',
    beatId: 'mall-stop',
    position: { x: 43.4, y: 65.8 },
    facing: -0.12,
    motion: 'idle',
    duration: 900,
    cue: 'Status mirror confirms the fit. Radio Rooftop route is cleared.',
    marketArrival: true,
    boutiqueLights: true,
    outfitUpgrade: true,
    jewelryUpgrade: true,
    statusUpgrade: true,
    vehicleOffset: { x: 0.74, z: 0.56 },
  },
  {
    id: 'back-to-suv',
    label: 'Back to SUV',
    beatId: 'radio-arrival',
    position: { x: 62, y: 54 },
    facing: 0.28,
    motion: 'idle',
    duration: 900,
    cue: 'Mr. Stone is back in motion. Next slice: Radio building arrival and rooftop elevator.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    routePulse: true,
    billboardSweep: true,
    outfitUpgrade: true,
    jewelryUpgrade: true,
    statusUpgrade: true,
    vehicleOffset: { x: 0, z: 0 },
  },
]

export const staticCityRadioSequence = [
  {
    id: 'radio-curb-arrival',
    label: 'Radio curb arrival',
    beatId: 'radio-arrival',
    position: { x: 62, y: 54 },
    facing: 0.28,
    motion: 'idle',
    duration: 850,
    cue: 'SUV stops at STATIC Radio. Security lights and broadcast signage lock onto Mr. Stone.',
    radioBoot: true,
    vehicleDoorOpen: true,
    radioArrival: true,
    broadcastLights: true,
    vehicleOffset: { x: 0.44, z: 0.48 },
  },
  {
    id: 'security-clear',
    label: 'Security clears path',
    beatId: 'radio-arrival',
    position: { x: 61.4, y: 54.5 },
    facing: 0.4,
    motion: 'walking',
    duration: 950,
    cue: 'Security recognizes the status pass. Crowd opens a path to the private elevator.',
    radioArrival: true,
    broadcastLights: true,
    securityClear: true,
    statusUpgrade: true,
    vehicleOffset: { x: 0.88, z: 0.72 },
  },
  {
    id: 'radio-elevator',
    label: 'Rooftop elevator',
    beatId: 'radio-arrival',
    position: { x: 60.8, y: 55.1 },
    facing: 0.08,
    motion: 'walking',
    duration: 1050,
    cue: 'Elevator opens into the broadcast tower. Rooftop audio rises above the city.',
    radioArrival: true,
    broadcastLights: true,
    securityClear: true,
    elevatorCue: true,
    vehicleOffset: { x: 1.2, z: 0.98 },
  },
  {
    id: 'rooftop-reveal',
    label: 'Rooftop reveal',
    beatId: 'vip',
    position: { x: 58, y: 61 },
    facing: -0.35,
    motion: 'idle',
    duration: 1000,
    cue: 'Doors open onto STATIC Radio Rooftop. DJ booth, skyline, and crowd movement come online.',
    rooftopReveal: true,
    broadcastLights: true,
    crowdHeat: true,
  },
  {
    id: 'vip-escort',
    label: 'VIP escort',
    beatId: 'vip',
    position: { x: 58.8, y: 60.6 },
    facing: -0.58,
    motion: 'walking',
    duration: 1100,
    cue: 'A host walks Mr. Stone through the crowd toward the VIP couch.',
    rooftopReveal: true,
    vipEscort: true,
    crowdHeat: true,
  },
  {
    id: 'drink-cigar',
    label: 'Drink and cigar',
    beatId: 'vip',
    position: { x: 59.2, y: 60.2 },
    facing: -0.62,
    motion: 'idle',
    duration: 1050,
    cue: 'Bottle service lands. Drink and cigar props confirm the VIP table state.',
    rooftopReveal: true,
    vipEscort: true,
    drinkProp: true,
    cigarProp: true,
    crowdHeat: true,
  },
  {
    id: 'vip-couch',
    label: 'VIP couch',
    beatId: 'vip',
    position: { x: 58.7, y: 60.8 },
    facing: -0.8,
    motion: 'idle',
    duration: 1000,
    cue: 'Mr. Stone sits in VIP while the rooftop dances around him. Vibe Mode route is queued.',
    rooftopReveal: true,
    seatedVip: true,
    drinkProp: true,
    cigarProp: true,
    crowdHeat: true,
  },
  {
    id: 'vibe-handoff',
    label: 'Vibe Mode queued',
    beatId: 'vibe-mode',
    position: { x: 32, y: 82 },
    facing: -1.1,
    motion: 'idle',
    duration: 900,
    cue: 'VIP beat complete. Next slice: SUV window down, first-person strip view, STATIC Blues.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    routePulse: true,
    billboardSweep: true,
    drinkProp: true,
    cigarProp: true,
    vehicleOffset: { x: 0, z: 0 },
  },
]

export const staticCityVibeSequence = [
  {
    id: 'vibe-suv-reentry',
    label: 'Back in SUV',
    beatId: 'vibe-mode',
    position: { x: 32, y: 82 },
    facing: -1.1,
    motion: 'idle',
    duration: 850,
    cue: 'Mr. Stone gets back in the SUV. The cabin shifts from rooftop heat into late-night strip mode.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    vibeMode: true,
    staticBlues: true,
    vehicleOffset: { x: 0, z: 0 },
  },
  {
    id: 'window-down',
    label: 'Window down',
    beatId: 'vibe-mode',
    position: { x: 32, y: 82 },
    facing: -1.1,
    motion: 'idle',
    duration: 1000,
    cue: 'Window lowers. The camera slides into first person and the city ambience spills into the cabin.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    vibeMode: true,
    windowDown: true,
    firstPersonDrive: true,
    staticBlues: true,
    cityWind: true,
    stripCruise: true,
    routePulse: true,
    billboardSweep: true,
    vehicleOffset: { x: 0, z: 0 },
  },
  {
    id: 'strip-cruise-low',
    label: 'STATIC Strip cruise',
    beatId: 'vibe-mode',
    position: { x: 36, y: 80 },
    facing: -0.98,
    motion: 'driving',
    duration: 1100,
    cue: 'First-person view looks past the window frame at STATIC Strip skyscrapers, wet road glow, and moving billboards.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    vibeMode: true,
    windowDown: true,
    firstPersonDrive: true,
    staticBlues: true,
    cityWind: true,
    stripCruise: true,
    routePulse: true,
    billboardSweep: true,
    vehicleOffset: { x: 0, z: 0 },
  },
  {
    id: 'billboard-canyon',
    label: 'Billboard canyon',
    beatId: 'vibe-mode',
    position: { x: 42, y: 74 },
    facing: -0.82,
    motion: 'driving',
    duration: 1150,
    cue: 'Billboards sweep overhead. STATIC Blues stays on the dash while the city becomes the music video.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    vibeMode: true,
    windowDown: true,
    firstPersonDrive: true,
    staticBlues: true,
    cityWind: true,
    stripCruise: true,
    routePulse: true,
    billboardSweep: true,
    vehicleOffset: { x: 0, z: 0 },
  },
  {
    id: 'return-camera-pullout',
    label: 'Camera pulls out',
    beatId: 'return-tower',
    position: { x: 50, y: 60 },
    facing: -0.64,
    motion: 'driving',
    duration: 1100,
    cue: 'The camera leaves first person and cuts wide behind the SUV as the route bends back toward the mountain.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    staticBlues: true,
    returnDrive: true,
    routePulse: true,
    billboardSweep: true,
    vehicleOffset: { x: 0, z: 0 },
  },
  {
    id: 'summit-road',
    label: 'Summit road',
    beatId: 'return-tower',
    position: { x: 56, y: 38 },
    facing: -0.52,
    motion: 'driving',
    duration: 1200,
    cue: 'Far third-person shot: the black SUV climbs the mountain road and STATIC Tower takes over the skyline.',
    radioBoot: true,
    vehicleDriving: true,
    playerInVehicle: true,
    staticBlues: true,
    returnDrive: true,
    towerApproach: true,
    routePulse: true,
    vehicleOffset: { x: 0, z: 0 },
  },
  {
    id: 'tower-valet-return',
    label: 'Tower valet return',
    beatId: 'return-tower',
    position: { x: 60, y: 25 },
    facing: -0.34,
    motion: 'idle',
    duration: 950,
    cue: 'SUV pulls back into STATIC Tower valet. Door opens and the mission returns to property state.',
    radioBoot: true,
    vehicleDoorOpen: true,
    playerInVehicle: true,
    towerApproach: true,
    vehicleOffset: { x: 0.5, z: 0.42 },
  },
  {
    id: 'tip-valet',
    label: 'Tip valet',
    beatId: 'return-tower',
    position: { x: 59.4, y: 25.6 },
    facing: -0.22,
    motion: 'walking',
    duration: 950,
    cue: 'Mr. Stone steps out, tips valet, and the SUV settles under the tower lights.',
    vehicleDoorOpen: true,
    towerApproach: true,
    valetTip: true,
    statusUpgrade: true,
    vehicleOffset: { x: 0.72, z: 0.52 },
  },
  {
    id: 'tower-doors-close',
    label: 'Tower doors close',
    beatId: 'return-tower',
    position: { x: 52, y: 12 },
    facing: Math.PI * 0.12,
    motion: 'walking',
    duration: 1050,
    cue: 'Tower doors close behind him. Opening-night route is complete and ready for the next playable system.',
    towerApproach: true,
    valetTip: true,
    missionComplete: true,
  },
]

export const mrStoneMissionBeats = [
  {
    id: 'wake',
    nodeId: 'penthouse-spawn',
    label: 'Wake Up',
    sceneZone: 'penthouse',
    camera: 'interior-third-person',
    location: 'STATIC Tower / Top-floor penthouse',
    objective: 'Mr. Stone wakes up in the top-floor penthouse. The city is below him and the first route objective loads.',
    stageDirection: 'Bedroom lights come alive, skyline reflection hits the glass, subtle STATIC tower hum underneath.',
    systemNeeds: ['property spawn', 'interior scene', 'character rig', 'wake/idle animation'],
  },
  {
    id: 'walk-to-elevator',
    nodeId: 'penthouse-elevator',
    label: 'Elevator',
    sceneZone: 'penthouse',
    camera: 'follow-cam',
    location: 'Private penthouse hallway',
    objective: 'Walk out of the penthouse and enter the private elevator.',
    stageDirection: 'Camera follows behind. Door opens with gold tower lighting. Elevator panel shows valet floor.',
    systemNeeds: ['pathfinding', 'door interaction', 'elevator transition', 'interior streaming'],
  },
  {
    id: 'valet',
    nodeId: 'summit-valet',
    label: 'Valet',
    sceneZone: 'valet',
    camera: 'cinematic-third-person',
    location: 'STATIC Tower valet floor',
    objective: 'Exit elevator, wait for the luxury SUV, get in, and trigger STATIC Radio.',
    stageDirection: 'Valet pulls up the black SUV. Door opens. Radio display boots with STATIC Blues queued.',
    systemNeeds: ['vehicle spawn', 'NPC valet shell', 'enter vehicle animation', 'radio session state'],
  },
  {
    id: 'drive-to-radio',
    nodeId: 'neon-drive',
    label: 'Drive',
    sceneZone: 'vehicle',
    camera: 'vehicle-chase',
    location: 'Mountain descent / Neon Rise',
    objective: 'Drive from STATIC Tower down toward Market Walk before the rooftop.',
    stageDirection: 'Wide chase camera, city lights streak, Radio comes alive, billboards react to Mr. Stone route and mall arrival.',
    systemNeeds: ['route camera path', 'vehicle path', 'billboard queue', 'ambient traffic'],
  },
  {
    id: 'mall-stop',
    nodeId: 'market-walk',
    label: 'Mall Stop',
    sceneZone: 'market',
    camera: 'shopping-third-person',
    location: 'Market Walk / Luxury retail floor',
    objective: 'Stop at the mall, buy clothes and jewelry, and update Mr. Stone’s visible status before the rooftop.',
    stageDirection: 'SUV pulls up to Market Walk. Boutique lights flare. Jewelry case opens. Fit/status updates before he exits back to the vehicle.',
    systemNeeds: ['storefront interaction', 'wardrobe inventory', 'jewelry inventory', 'outfit swap', 'status update'],
  },
  {
    id: 'radio-arrival',
    nodeId: 'radio-building',
    label: 'Radio Arrival',
    sceneZone: 'venue',
    camera: 'arrival-walk',
    location: 'STATIC Radio entrance',
    objective: 'Pull up, step out, enter the Radio building, and ride elevator to rooftop.',
    stageDirection: 'SUV stops at curb. Crowd audio rises. Security recognizes Mr. Stone and clears the path.',
    systemNeeds: ['arrival marker', 'vehicle exit animation', 'building interior portal', 'security NPC shell'],
  },
  {
    id: 'vip',
    nodeId: 'radio-rooftop',
    label: 'VIP Rooftop',
    sceneZone: 'venue',
    camera: 'social-third-person',
    location: 'STATIC Radio rooftop party',
    objective: 'Escort Mr. Stone to VIP, give him a drink and cigar, then seat him on the VIP couch while people dance.',
    stageDirection: 'Host greets him. Bottle service glow. Crowd dances around the rooftop while the skyline breathes.',
    systemNeeds: ['VIP seat interaction', 'drink prop', 'cigar prop', 'crowd NPC loops', 'rooftop audio'],
  },
  {
    id: 'vibe-mode',
    nodeId: 'vibe-strip',
    label: 'Vibe Mode',
    sceneZone: 'vehicle',
    camera: 'first-person-window',
    location: 'STATIC Strip',
    objective: 'Get back in the SUV, turn on Vibe Mode, roll down the window, and look out at the skyscrapers while STATIC Blues plays.',
    stageDirection: 'Camera slides into first person. Window lowers. City wind, crowd spillover, neon reflections, blues track.',
    systemNeeds: ['first-person camera', 'window animation', 'city ambience', 'rights-safe Static Blues asset'],
  },
  {
    id: 'return-tower',
    nodeId: 'tower-return',
    label: 'Return',
    sceneZone: 'vehicle',
    camera: 'far-third-person',
    location: 'Mountain road back to STATIC Tower',
    objective: 'Far third-person shot follows the SUV back up the mountain. Mr. Stone exits, tips valet, and walks back in.',
    stageDirection: 'Camera pulls wide. STATIC Tower dominates the summit. Valet gets tipped. Doors close behind him.',
    systemNeeds: ['return route camera', 'tip valet interaction', 'mission completion state', 'property return spawn'],
  },
]

export const staticCityMissionLoop = mrStoneMissionBeats

export const staticCitySystems = [
  ['STATIC ID', 'One account connects web, mobile, future Unreal client, console, VR, haptics, Entity ownership, inventory, companions, vehicles, and event access.'],
  ['Create-a-player', 'Face/body builder, wardrobe, jewelry, animations, mic identity, optional voice effects, and persistence.'],
  ['Property/spawn', 'Starter rooms, apartments, businesses, penthouses, mansions, castles, suites, and landmark spawn rules.'],
  ['Vehicle/travel', 'Valet, vehicle classes, route selection, cinematic travel clips, and later controllable driving.'],
  ['STATIC Sports', 'Basketball first: arena nights, fan heat, VIP watch parties, creator teams, and playable sports only after real physics/netcode exist.'],
  ['Velocity/racing', 'Red-light challenges, deep car customization, night runs, car shows, takeover zones, and non-cash reputation rewards before any real-value wagering.'],
  ['Dominion/factions', 'Crews, alliances, district-control windows, fortress upgrades, treaty blocs, arcade loadouts, and survival-wave events as opt-in game modes.'],
  ['Companions/guardians', 'Cute sidekicks, guardian bodyguards, robots, dragons, golems, companion squads, stance, loadouts, and opt-in protection behavior.'],
  ['Story campaign', 'GTA-style cinematic open-world chapters with better controls, more realistic graphics, and STATIC creator/social systems; origin missions prove the first slice.'],
  ['Enterable interiors', 'Hero interiors are authored, repeatable interiors are templated, towers use lobby/elevator/instanced floors, and background buildings stay facade-only until needed.'],
  ['Mall/marketplace', 'Clothing, jewelry, skins, accessories, memberships, wishlists, drops, and payments later.'],
  ['Radio rooftop', 'Ambient venue, station UI, now playing, lounge props, and rights-safe/static-made music.'],
  ['Social presence', 'NPC shells, friends/follows, then real multiplayer only after auth, privacy, and moderation.'],
  ['Venue events', 'Concerts, red carpets, premieres, creator drops, crowd heat, and Signals aftershock.'],
  ['Inventory/status', 'Visible fit, vehicle, property, event attendance, access passes, and progression state.'],
]

export const staticCityBackendContracts = [
  ['profiles', 'Supabase user profile, display name, handle, role, privacy, moderation status.'],
  ['platform_links', 'Cross-platform login links for web, mobile, PC/console, VR, haptic devices, and future game clients.'],
  ['entities', 'Account-bound Entity identity, body/style choices, current spawn, active outfit, mic/effects settings.'],
  ['entity_loadouts', 'Active outfit, vehicle, property, companion slots, status tier, and visibility state for a playable Entity.'],
  ['property_access', 'Approved/owned spawn locations, businesses, hotel suites, penthouses, mansions, and landmark rights.'],
  ['inventory_items', 'Wardrobe, jewelry, props, vehicles, passes, skins, and future paid entitlements.'],
  ['world_sessions', 'Current route, scene, position, camera state, client type, vehicle, property, and session status across web/game clients.'],
  ['signals_social', 'Follows, saves, comments, public posts, clips, drop announcements, and event aftershock.'],
  ['radio_sessions', 'Station schedule, now playing, host, rights source, simulcast, and user listening state.'],
  ['presence_events', 'NPC shells, friend presence, room occupancy, event heat, reports, bans, and moderation gates.'],
  ['story_missions', 'Mission definitions, chapter arc, beat order, cinematic intent, unlock rules, district dependencies, reward intent, and public/internal visibility.'],
  ['mission_progress', 'Per-account mission state, active beat, completed beats, failed/abandoned state, replay permission, and reward issuance.'],
  ['building_interiors', 'Interior type, building link, hero/template/lobby/facade/event tier, access rules, streaming target, and moderation status.'],
  ['interior_instances', 'Instanced apartment/shop/office/hotel-room state, furniture template, owner access, spawn markers, and reset rules.'],
  ['age_gates', 'Mature venue access policy, consent/version state, moderation locks, region/legal flags, and audit trail for hidden nightlife content.'],
  ['vehicle_builds', 'Account-bound vehicle ownership/customization, paint, wraps, wheels, underglow, suspension, audio, interior, and moderation state.'],
  ['race_sessions', 'Instanced race route, challenger type, non-cash stake, route validation, result, replay pointer, and anti-cheat status later.'],
  ['sports_events', 'Arena schedules, sport type, teams, venue route, spectator state, rights/moderation notes, and event heat.'],
  ['arena_sessions', 'Playable or watch-party sports session state, participants, score shell, court route, replay pointer, and validation status later.'],
  ['team_rosters', 'Creator/studio/crew team membership, role, jersey/skin reference, moderation state, and league-season eligibility.'],
  ['crews', 'Crew profile, owner, roles, banner, home base, moderation status, privacy, recruitment state, and seasonal reputation.'],
  ['territory_control', 'Seasonal district-control state, treaty bloc, visual ownership, contested windows, cooldowns, and reset schedule.'],
  ['conflict_sessions', 'Opt-in arcade conflict instance, crew participants, ruleset, loadout class, result validation, replay pointer, and anti-cheat status later.'],
  ['fortress_upgrades', 'Non-cash district visual upgrades, walls, gates, shields, turrets, command rooms, event stage, and entitlement limits.'],
  ['companions', 'Account-bound companion identity, species/type, scale class, current skin, animation set, owner, moderation state, and safety flags.'],
  ['companion_slots', 'Active companion/bodyguard slots, follow/protect mode, district permissions, performance budget, and opt-in conflict availability.'],
]

export const staticCityVisualTargets = [
  {
    id: 'arrival-cinema',
    title: 'Arrival District fidelity',
    image: '/assets/static-arrival-district.png',
    copy: 'The world should feel like the generated Arrival District: dense, cinematic, social, expensive, wet streets, moving light, and venue signage everywhere.',
  },
  {
    id: 'signals-street',
    title: 'Signals as street culture',
    image: '/assets/static-signals-boulevard.png',
    copy: 'Signals should become people, phones, billboards, drops, clips, crowd heat, and creator pulse inside the city.',
  },
  {
    id: 'radio-rooftop',
    title: 'Radio as destination',
    image: '/assets/static-radio-rooftop.png',
    copy: 'Radio is not a playlist screen. It is a rooftop venue, broadcast desk, skyline, crowd, host layer, and Vibe Mode soundtrack.',
  },
  {
    id: 'play-gate',
    title: 'PLAY as a portal district',
    image: '/assets/static-play-world-gate.png',
    copy: 'STATIC PLAY should feel like walking into playable worlds, arenas, lounges, limited modes, and creator-made game entrances.',
  },
  {
    id: 'sports-arena',
    title: 'Arena and fan gravity',
    image: '/assets/static-arrival-district.png',
    copy: 'The Arrival District image already implies sports nights, VIP tables, fan movement, and arena heat. Basketball should be the first playable sport lane.',
  },
]

export const staticCityDistrictBillboards = [
  {
    id: 'summit-arrival-board',
    nodeId: 'static-tower',
    title: 'ARRIVE. CONNECT. LIVE.',
    src: '/assets/static-arrival-district.png',
    x: 51,
    y: 13,
    width: 4.3,
    height: 2.45,
    elevation: 4.2,
    rotation: -0.25,
    tone: '#fff0ca',
  },
  {
    id: 'signals-strip-board',
    nodeId: 'signal-strip',
    title: 'SIGNALS LIVE',
    src: '/assets/static-signals-boulevard.png',
    x: 28,
    y: 77,
    width: 4.1,
    height: 2.3,
    elevation: 2.2,
    rotation: 0.42,
    tone: '#e56cff',
  },
  {
    id: 'radio-rooftop-board',
    nodeId: 'radio-rooftop',
    title: 'STATIC RADIO',
    src: '/assets/static-radio-rooftop.png',
    x: 64,
    y: 61,
    width: 4,
    height: 2.25,
    elevation: 2.85,
    rotation: -0.55,
    tone: '#9d63ff',
  },
  {
    id: 'play-world-board',
    nodeId: 'play-gate',
    title: 'STATIC PLAY',
    src: '/assets/static-play-world-gate.png',
    x: 75,
    y: 48,
    width: 3.85,
    height: 2.18,
    elevation: 2.7,
    rotation: -0.74,
    tone: '#a364ff',
  },
  {
    id: 'static-arena-board',
    nodeId: 'static-arena',
    title: 'STATIC ARENA',
    src: '/assets/static-arrival-district.png',
    x: 48,
    y: 49,
    width: 3.9,
    height: 2.2,
    elevation: 3,
    rotation: -0.1,
    tone: '#ff7a2f',
  },
  {
    id: 'club-static-board',
    nodeId: 'club-static',
    title: 'CLUB STATIC',
    src: '/assets/static-arrival-district.png',
    x: 67,
    y: 66,
    width: 3.45,
    height: 1.95,
    elevation: 2.25,
    rotation: -0.35,
    tone: '#e56cff',
  },
  {
    id: 'market-walk-board',
    nodeId: 'market-walk',
    title: 'MARKET WALK',
    src: '/assets/static-marketplace-boulevard.png',
    x: 39,
    y: 65,
    width: 3.65,
    height: 2.08,
    elevation: 2.25,
    rotation: 0.34,
    tone: '#ffb45e',
  },
  {
    id: 'studio-tower-board',
    nodeId: 'crown-ridge',
    title: 'CREATOR TOWER',
    src: '/assets/static-studio-tower.png',
    x: 36,
    y: 34,
    width: 3.55,
    height: 2,
    elevation: 3.35,
    rotation: 0.16,
    tone: '#d8ad68',
  },
]
